import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { User } from '../types';

export const exportStudentData = (user: User) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(41, 128, 185);
  doc.text('NeuroLearn AI - Student Report', 14, 20);
  
  // Student Info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Name: ${user.name}`, 14, 35);
  doc.text(`Email: ${user.email}`, 14, 42);
  doc.text(`Level: ${user.level} (XP: ${user.xp})`, 14, 49);
  doc.text(`Study Streak: ${user.studyStreak} days`, 14, 56);
  
  // Wellbeing Stats
  doc.setFontSize(16);
  doc.setTextColor(41, 128, 185);
  doc.text('Wellbeing Metrics', 14, 70);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Health Score: ${user.healthScore}/100`, 14, 80);
  doc.text(`Focus Level: ${user.focusLevel}/100`, 14, 87);
  doc.text(`Burnout Risk: ${user.burnoutRisk}`, 14, 94);
  
  // Last Quiz
  if (user.lastQuizScore !== undefined) {
    doc.setFontSize(16);
    doc.setTextColor(41, 128, 185);
    doc.text('Recent Assessment', 14, 110);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Subject: ${user.lastQuizSubject || 'General'}`, 14, 120);
    doc.text(`Score: ${user.lastQuizScore}%`, 14, 127);
  }
  
  // Subjects Table
  doc.setFontSize(16);
  doc.setTextColor(41, 128, 185);
  const tableStartY = user.lastQuizScore !== undefined ? 145 : 110;
  doc.text('Subject Progress', 14, tableStartY);
  
  const tableData = user.subjects.map(sub => [
    sub.name,
    `${sub.progress}%`,
    `${sub.completedHours} / ${sub.targetHours} hrs`
  ]);
  
  // @ts-ignore - jspdf-autotable extends jsPDF but types might not perfectly align
  doc.autoTable({
    startY: tableStartY + 10,
    head: [['Subject', 'Progress', 'Hours']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] }
  });
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by NeuroLearn AI on ${new Date().toLocaleDateString()}`, 14, doc.internal.pageSize.height - 10);
  
  doc.save(`NeuroLearn_Report_${user.name.replace(' ', '_')}.pdf`);
};
